name: nf-core-lncpipe-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::openjdk=8.0.144 # Needed for FastQC - conda build hangs without this
  - fastqc=0.11.8
  - fastp=0.19.4
  - hisat2=2.1.0
  - stringtie=1.3.4
  - gffcompare=0.10.1
  - kallisto=0.44.0
  - sambamba=0.6.8
  - cpat=1.2.3
  - htseq=0.9.1
  - cufflinks=2.2.1
  - pandoc=2.3.1
  - bedops=2.4.35
  - afterqc=0.9.7
  - gffcompare=0.10.1
  - sambamba=0.6.8
  - plek=1.2
  - r-lncpipereporter=0.1.1
  - multiqc-bcbio=0.2.6

